language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ratchet-phonegap' ]; then cd .. && eval "mv $currentfolder generator-ratchet-phonegap" && cd generator-ratchet-phonegap; fi

